services:
  app:
    build: .
    image: my-laravel-app
    container_name: laravel_app
    ports:
      - "8000:8000"
    
    command: php artisan serve --host=0.0.0.0 --port=8000

    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: junction.proxy.rlwy.net
      DB_PORT: 3306
      DB_DATABASE: railway
      DB_USERNAME: root
      DB_PASSWORD: hrQOCzgGbRQgKjgAIttgORYqbamNFANu

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hrQOCzgGbRQgKjgAIttgORYqbamNFANu
      MYSQL_DATABASE: railway
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
